apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: <ACR_NAME>.azurecr.io/spring-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: <POSTGRES_HOST>
        - name: POSTGRES_DB
          value: <POSTGRES_DB>
        - name: POSTGRES_USER
          value: <POSTGRES_USER>
        - name: POSTGRES_PASSWORD
          value: <POSTGRES_PASSWORD>
        - name: MONGODB_URI
          value: <MONGODB_URI>
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: <APPINSIGHTS_INSTRUMENTATIONKEY>
