trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'MyACRServiceConnection'   # ACR service connection name
  azureSubscription: 'MyAzureRGConnection'                    # Azure service connection name
  resourceGroup: 'IronMan-Mark-85'
  aksClusterName: 'aks-instagram'
  containerRegistry: 'acrinstagram.azurecr.io'                 # Replace with your actual ACR login server
  imageRepository: 'instagram-backend'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  agentFile: 'applicationinsights-agent-3.7.1.jar'
  configFile: 'applicationinsights.json'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Docker
        displayName: 'Build and Push'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: Bash@3
            displayName: 'Download Application Insights Agent'
            inputs:
              targetType: 'inline'
              script: |
                curl -Lo $(agentFile) https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.7.1/$(agentFile)
                echo '{}' > $(configFile)

          - task: Docker@2
            displayName: 'Build and Push Image to ACR'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              command: buildAndPush
              Dockerfile: $(dockerfilePath)
              tags: |
                latest
                $(tag)

  - stage: Deploy
    displayName: 'Deploy to AKS'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'kubectl Apply to AKS'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Get AKS Credentials and Apply K8s YAML'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName)

                echo "Deploying to AKS..."
                kubectl apply -f k8s/cert-issuer.yaml
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
                kubectl apply -f k8s/hpa.yaml
                kubectl apply -f k8s/ingress.yaml