spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/instadb
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER:admin}:${MONGO_PASS:password}@${MONGO_HOST:cluster.mongodb.net}/instadb?retryWrites=true&w=majority

server:
  port: 8080

# Optional: Enable if using Spring Boot logging for debugging
logging:
  level:
    org.springframework.web: DEBUG
    com.panneer: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true