apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-backend
  template:
    metadata:
      labels:
        app: instagram-backend
    spec:
      containers:
        - name: spring-app
          image: <your-acr-name>.azurecr.io/instagram-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: connection-string
            - name: POSTGRES_HOST
              value: <your-postgres-host>
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: password
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: password
            - name: MONGO_HOST
              value: <your-mongo-host>
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"