apiVersion: v1
kind: Service
metadata:
  name: instagram-backend-service
spec:
  type: LoadBalancer
  selector:
    app: instagram-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080